### PR TITLE
Fixed issue with install script when using '-d' with a directory containing spaces

### PR DESCRIPTION
**Pull request by hwittenborn**
The install script currently janks up like crazy if you run something like this:

```sh
./install.sh -d 'directory with spaces'
```

This PR fixes the issue, which pretty much just adds quotes around some variables to ensure everything functions properly.

---

Closes https://github.com/vinceliuice/Matcha-gtk-theme/issues/175

### CODE REVIEW

**Comment by vinceliuice** [comment]
Thanks!

**Comment by hwittenborn** [comment]
Would you be able to make a new release as well? I'd like to package this for Debian under a versioned release, and this was the thing stopping me from doing so.

**Comment by vinceliuice** [comment]
No problem!

**Comment by hwittenborn** [comment]
Looks great! Thanks! :smiley:

**Comment by hwittenborn** [comment]
If it's any concern where the Debian package is located, you can find it [here](https://dur.hunterwittenborn.com/packages/matcha-gtk-theme/).

**Pull request merged**
